title: Poradnia RiRi
description: Poradnia RiRi - Strona internetowa Fundacji RiRi
locale: pl

collections:
  aktualnosci:
    output: true
  turnusy:
    output: true
  kadra:
    output: true
    permalink: /kadra/:name/
